version: '3.9'
services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=recipe_api_db
      - POSTGRES_USER=recipe_user
      - POSTGRES_PASSWORD=password
  app:
    build: 
      context: .
      args:
        - DEV=true
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=recipe_api_db
      - DB_USER=recipe_user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  postgresql: {}
