version: '3'
services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  postgresql: